### ISSUE TITLE
Test behavior of media player/stream progress

### ISSUE THREAD

**Issue by bedeho** [JoyStream/joystream-desktop#731]
1. when torrent goes from streaming to fully downloaded. 
2. Seeking a fully downloaded torrent (could a delay/buffering cause the progress bar to appear?). (Progress bar and paid download button should never appear)

**Comment by mnaamani** [comment]
I can't seem to produce this edge case where a video element will fire the waiting event (waiting for next video frame to buffer) for a completed download. But I open this https://github.com/JoyStream/joystream-desktop/pull/744 just to be sure we never display the stream progress if it ever does happen.

We probably need to show some other indicator that video is buffering, maybe due to delay with disk io.

**Comment by bedeho** [comment]
Done in https://github.com/JoyStream/joystream-desktop/pull/744
